spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  # todo 개발 데이터베이스 연결
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
